stellar/binaries

.github/workflows/release-test.yml
Change release test to workflow dispatch.
Unfortunately the workflow cannot be automatically triggered because the release is created in a workflow, and releases created from workflows are not allowed to kick off other workflows.
=> Change release test to workflow dispatch

.github/workflows/build.yml
Add cargo-edit.
To use in place of cargo workspaces for upgrading versions during the release process.
=> Add cargo-edit

.github/workflows/build.yml
Add cargo-hack v0.5.28.
Cargo-hack v0.5.28 adds a new option `--print-command-list` (https://github.com/taiki-e/cargo-hack/pull/175#issuecomment-1336348423). The option makes it possible to use cargo-hack to build a command list without actually executing the commands, as it does today.
This will allow us to build dynamic matrices for GitHub builds that are getting really big, like the stellar-xdr crate.
We've experimented with this feature pre-release in https://github.com/stellar/rs-stellar-xdr/pull/212.
=> Add cargo-hack v0.5.28

.github/workflows/build.yml
Add cargo-fuzz v0.11.2
For use in stellar/rs-soroban-sdk#957.
=> Add cargo-fuzz v0.11.2

.github/workflows/build.yml
Add soroban-cli to binaries cached for ci builds.
The soroban-examples repo will need soroban-cli installed in ci runs.
=> Add soroban-cli to binaries cached for ci builds

.github/workflows/build.yml
Add cargo-semver-checks and cargo-public-api.
For use in the rs-soroban-sdk CI for identifying breakages in the API compatibility of the library. Experimenting with both.
For stellar/rs-soroban-sdk#1195
=> Add cargo-semver-checks and cargo-public-api

.github/workflows/build.yml
Update cargo-fuzz to 0.12.0
Use the latest version in a soroban-sdk job that is failing with an error when using a newer version of rust.
=> Update cargo-fuzz to 0.12.0

.github/workflows/build.yml
Add wasm-pack 0.12.1
For use in the rs-stellar-xdr repo to generate language bindings for JavaScript.
=> Add wasm-pack 0.12.1

.github/workflows/build.yml
Build binaries for macOS amd64 and arm64
I started to see builds fail because `macos-latest` appears to now map to `macos-14-arm` rather than `macos-14`. An example of a build I saw fail is: https://github.com/stellar/rs-soroban-sdk/actions/runs/8815533346/job/24197683380?pr=1261
=> Build binaries for macOS amd64 and arm64

.github/workflows/build.yml
This is part of making https://github.com/stellar/rs-soroban-env/pull/1416 work -- we will need to run a new binary during CI
=> Add check-lockfile-intersection to binaries list

.github/workflows/build.yml
Add wasm-bindgen-cli v0.2.92.
To use alongside wasm-pack in the js-stellar-xdr-json library.
N/A
=> Add wasm-bindgen-cli v0.2.92

.github/workflows/build.yml
Fix CI breakage due to Rustdocs https://github.com/stellar/rs-soroban-env/actions/runs/9618744429/job/26533277451
[TODO: Why this change is being made. Include any context required to understand the why.]
[TODO or N/A]
=> Bump cargo-semver-checks to 0.32.0

.github/workflows/build.yml
Add cargo-workspaces 0.3.4.
For use in the rust-publish-dry-run-v2 workflow in stellar/actions.
=> Add cargo-workspaces 0.3.4

.github/workflows/build.yml
Add CI concurrency group limiting to one build per branch, including main, canceling any older runs.
Limit CI resource usage, especially of mac and windows instances. We never need out-of-date commit CI runs to complete, even on main.
=> Add CI concurrency group

.github/workflows/build.yml
Add actionlint binary to our ci prebuilds.
For use in stellar/actions CI checks in https://github.com/stellar/actions/pull/77.
=> Add actionlint

.github/workflows/build.yml
semver-checks started failing on nightly due to changes in rustdoc's internals. see https://github.com/obi1kenobi/cargo-semver-checks/pull/825
=> Bump cargo-semver-checks to 0.35

.github/workflows/build.yml
Change the version of the go commands built so the version string is just "1.7.1" instead of "v1.7.1"
The version is used in the resulting file that gets uploaded to the releases.
The version of go builds has a v in the file name, and the version of cargo builds has no v in the filename.
For consistency with the cargo commands that are built.
=> Make version of go builds consistent with cargo builds

.github/workflows/build.yml
Add cargo-deny with both versions 0.14.19 and 0.16.1.
We use 0.14.19 currently on multiple repos and will likely use 0.16.1 soon on new repos.
N/A
=> Add cargo-deny

.github/workflows/build.yml
Bump cargo-semver-checks to 0.37.0
To fix Rust CI that expects the updated version
N/A
=> Bump cargo-semver-checks to 0.37.0

.github/workflows/build.yml
Bump download/upload artifact versions
v3 is deprecated and job automatically fails
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
N/A
=> Bump download/upload artifact version

.github/workflows/build.yml
Adds arm linux build
We need ARM binaries to use publish-dry-run on ARM runner
N/A
=> Enable ARM Linux

.github/workflows/build.yml
Update cargo-semver-checks to 0.40.0.
The version currently in use isn't compatible with newer versions of Rust.
Required for:
- https://github.com/stellar/rs-soroban-sdk/pull/1453
=> Update cargo-semver-checks to 0.40.0

.github/workflows/build.yml
Bump cargo-semver-checks to 0.41.0
Fix Rust CI
N/A
=> Bump cargo-semver-checks to 0.41.0

.github/workflows/build.yml
Update cargo-fuzz to 0.13.1.
Get latest version.
=> Update cargo-fuzz to 0.13.1

.github/workflows/build.yml
Update cargo-semver-checks to 0.42.0.
Get latest version due to current version not compatible with latest Rust:
- https://github.com/stellar/rs-soroban-sdk/actions/runs/16814809806/job/47629188058?pr=1528
=> Update cargo-semver-checks to 0.42.0

.github/workflows/build.yml
Update cargo-semver-checks to 0.44.0.
Required for building with Rust v1.90.
=> Update cargo-semver-checks to 0.44.0

.github/workflows/build.yml
Check for and reuse existing release artifacts before rebuilding. Only build new versions.
Reduce build times and resource usage by skipping redundant compilation and packaging steps when artifacts already exist in previous releases.
=> Reuse existing artifacts from prior releases

.github/workflows/build.yml
Change the release test to reference the action using the directory, not the filename.
Actions are referenced locally as a directory, not a filename.
=> Fix release-test

.github/workflows/build.yml
Update macOS runner versions to latest and add Linux arm64 support for Go builds.
Use latest macOS runners for better compatibility and performance. The arm64 Linux use on Go builds was missing.
=> Update macOS runner versions to latest and add Linux arm64 support for Go builds
